#!/bin/bash
set -o errexit -o nounset -o pipefail
set -x

cd /sys/class/gpio
N=27

test -d gpio$N || echo $N > export
cd gpio$N

echo out > direction
echo 0 > value

chgrp sousvide . value
chmod o+rx /sys/devices/platform/soc/*.gpio/gpiochip0
ln -sf $(readlink -f value) /run/sousvide-pin
