#!/bin/sh
set -o errexit -o nounset -o pipefail
set -x

cd /sys/class/gpio
N=17

test -d gpio$N || echo $N > export
cd gpio$N

echo out > direction
echo 0 > value

chgrp sousvide . value
ln -sf /etc/sousvide-pin $(readlink -f value)
